#!/usr/bin/env bash
# An infinite loop is created that displays "To infinity and beyond"
# it does so with sleep 2
# To stop press Ctrl-C

while true
do
    echo "To infinity and beyond"
    sleep 2
done
