#!/usr/bin/env bash
# Script kills another script running in another terminal (need -f to find pid)
# run the two scripts on different terminals to see the process

pkill -f "4-to_infinity_and_beyond"
